# Generated by Django 3.2 on 2022-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image7',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image8',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
