# Generated by Django 3.2 on 2022-04-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
