# Generated by Django 3.2 on 2022-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayapp', '0004_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_app', models.CharField(choices=[('Tony', 'Tony'), ('Matea', 'Matea'), ('Martina', 'Martina')], max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
