# Generated by Django 3.2 on 2022-04-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidayapp', '0005_apartmentprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentprice',
            old_name='name_of_app',
            new_name='apartment_name',
        ),
    ]
